name: Go Test

on:
  push:
    branches: ["main", "chore/upgrade-linter"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Linter
        run: make lint
      - name: Test
        run: make tests
